### PR TITLE
Check `toArray` also compatible with `__call` implementations

### LINKED ISSUE #19: convertValuetoArray($value) not compatible with __call()
Hi @hopeseekr ,

Thank you for your work, this package. I am using this in favor of the Spatie package because I also think DTOs should be immutable. 

I run into a problem with the `$dto->toArray()` method when I have a `\Illuminate\Http\UploadedFile` in the DTO. Because it has magic function `__call()` implemented (by the  `\Illuminate\Support\Traits\Macroable` trait), the next check always returns true (even when no `toArray` exists). Therefore I get this error: 

> Method Illuminate\Http\UploadedFile::toArray does not exist.

The problem is known: https://www.php.net/manual/en/function.is-callable.php#118623

In `\PHPExperts\SimpleDTO\SimpleDTO::convertValueToArray` there is this check for every data attribute value:

```php
        if (is_object($value)) {
            if (is_callable([$value, 'toArray']) && !($value instanceof Carbon)) {
                return $value->toArray();
            }

            if ($value instanceof \stdClass) {
                return (array) $value;
            }
        }
```

source: https://github.com/PHPExpertsInc/SimpleDTO/blob/f7b027eae78d16f8042b12ff4942e61e7321cd8f/src/SimpleDTO.php#L328

The problem: `is_callable` has trouble figuring out that `UploadedFile` has no callable `toArray`, it says `true` but instead it is `false`.

I think the following would fix the problem:

```php
        if (is_object($value)) {
            if (method_exists($value, 'toArray') && !($value instanceof Carbon)) {   // <=== this would work
                return $value->toArray();
            }

            if ($value instanceof \stdClass) {
                return (array) $value;
            }
        }
```

Would you consider implementing this fix?

### PR DESCRIPTION
**Pull request by ametad**
Closes #19

---
This change is [Reviewable](https://reviewable.io/reviews/phpexpertsinc/simpledto/20)

### CODE REVIEW

**Review by ametad — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/phpexpertsinc/simpledto/20#-:-MtD74W18FwmgoZM89gA:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by ametad** [comment]
I was not sure if I am supposed to do something... but I clicked the "revieable" button and more :smile:

**Comment by ametad** [comment]
Hi @hopeseekr,

Could you give me some feedback at my pull request? If you want me to do something about the code, please just ask.

**Review by ametad — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/phpexpertsinc/simpledto/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ametad)

**Comment by ametad** [comment]
@hopeseekr Would you be so kind and merge this?

**Review by hopeseekr — APPROVED** [review]

**Pull request merged**
